import { lazy } from "react"

export const Home = lazy(() => import("../pages/job-seeker/home/Home"))
export const Login = lazy(() => import("../pages/login/Login"))
export const Register = lazy(() => import("../pages/register/Register"))
export const ForgetPassword = lazy(() => import("../pages/forgetPassword/ForgetPassword"))
export const ResetPasswoerd = lazy(() => import("../pages/resetPassword/ResetPasswoerd"))
export const JobSearch = lazy(() => import("../pages/jobsearch/JobSearch"))
export const JobDetails = lazy(() => import("../pages/jobDetails/JobDetails"))
export const OrginizationDetails = lazy(() => import("../pages/orginaizationDetails/OrgiazationDetails"))
export const MyNetwork = lazy(() => import("../pages/job-seeker/myNetwork/MyNetwork"))
export const MyApplication = lazy(() => import("../pages/job-seeker/myApplication/MyApplication"))
export const Profile = lazy(() => import("../pages/job-seeker/profile/Profile"))
export const EditProfile = lazy(() => import("../pages/job-seeker/editProfile/EditProfile"))
export const CV = lazy(() => import("../pages/job-seeker/CV/CV"))
export const Massegee = lazy(() => import("../pages/job-seeker/massege/Massege"))
export const Notivigation = lazy(() => import("../pages/job-seeker/notevigation/Notivigation"))
export const AI = lazy(() => import("../pages/job-seeker/Ai/AI"))
export const Search = lazy(() => import("../pages/job-seeker/saerch/Saerch"))
export const Job = lazy(() => import("../pages/job-seeker/job/Job"))

export const Dashboard = lazy(() => import("../pages/Busines/Dashboard/Dashboard"))
export const PostJob = lazy(() => import("../pages/Busines/createorganization/PostJob"))
export const Application = lazy(() => import("../pages/Busines/application/Application"))
export const OrgProfile = lazy(() => import("../pages/Busines/orgprofile/OrgProfile"))
export const Analytics = lazy(() => import("../pages/Busines/analystics/Analystics"))
export const PostManaegJobs = lazy(() => import("../pages/Busines/post-manage-job/PostManaegJobs"))
